
name: "mnist_model_pytorch"
platform: "pytorch_libtorch"
max_batch_size: 4  # Enable dynamic batching
input [
  {
    name: "conv1"
    data_type: TYPE_FP32
    dims: [1, 1, 28, 28]  # Include the dynamic batch dimension
  }
]
output [
  {
    name: "fc2"
    data_type: TYPE_FP32
    dims: [1, 10]  # Include the dynamic batch dimension
  }
]
        